feature/dotnet container -> feature/dotnet-core (#6)
* database and machetecontainer talking

* move some old scripts into old Util

* a container that doesn't crash

* get rid of config transforms; kestrel stuck on cert

* update UI: npm audit fix

* docker container with no SSL; disable SSL

* reduce size of docker container

* add reverse proxy configuration, but aspnetcore rejects it

* working proxy!

* SSL working

* update UI

* fix Facebook; test oidc; working

* Docker, everything but OIDC. OIDC fails due to the fact that NginX is not
forwarding the Host headers, and so .netcore still 'thinks' it is running on
:4213 (Google):

System.Security.Authentication.AuthenticationException: Results: {
  "error": "redirect_uri_mismatch",
  "error_description": "Bad Request"
}

RedirectUri: http://localhost:4213/id/signin-google

(Should be https://localhost/id/signin-google, which should be "truth,"
according to the Request document.)

https://github.com/aspnet/Security/issues/1857#issuecomment-423220328
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#configure-nginx

Comb this and fix. Some of the groundwork has already been laid here.

Signing off, blah bleary 3 am

* finishing Docker container:

set Docker container scheme to HTTPS*
add httpcontext/cookie stuff to V2 signout; still doesn't work behind proxy
accept forwarded headers on the dotnet side
have proxy forward all the right headers
*set request scheme based on env var
flesh out instructions for running container

* add dependency that was breaking tests

* \n@EOF

* \n@eof

* fix UTF errors in LICENSE.txt

* delete how to apply boilerplate for LICENSE.txt

* PR follow-up for chaim1221/#6