Decorated MacheteContext with DbConfigurationType to solve Appveyor error
Test method Machete.Test.Integration.Service.WorkerSigninTests.LotterySignin threw exception:

System.TypeInitializationException: The type initializer for 'System.Data.Entity.MigrateDatabaseToLatestVersion`2' threw an exception. ---> System.InvalidOperationException: The default DbConfiguration instance was used by the Entity Framework before the 'AzureConfiguration' type was discovered. An instance of 'AzureConfiguration' must be set at application start before using any Entity Framework features or must be registered in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=260883 for more information.